---
title: "Homework 2 - P8105"
output: github_document
author: Grace Santos 
date: "2023-09-27"
---


```{r}
library(tidyverse)
```


## Problem 1 

```{r, pols_month}
pols_month_df = 
  read_csv("fte_data/pols-month.csv") |> 
  janitor::clean_names() |> #clean the dataset
  separate(mon, into = c("year", "month", "day")) |> #breakup mon into integer variables
  mutate(
    month = #replace month number with month name 
      case_match( 
        month, 
        "01" ~ "January",
        "02" ~ "Feburary",
        "03" ~ "March",
        "04" ~ "April",
        "05" ~ "May",
        "06" ~ "June",
        "07" ~ "July",
        "08" ~ "August",
        "09" ~ "September",
        "10" ~ "October",
        "11" ~ "November",
        "12" ~ "December")
  )
```

```{r, snp}
snp_df = 
  read_csv("fte_data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(date, into = c("month", "day", "year")) |> 
mutate(
    month = #replace month number with month name 
      case_match( 
        month, 
        "1" ~ "January",
        "2" ~ "Feburary",
        "3" ~ "March",
        "4" ~ "April",
        "5" ~ "May",
        "6" ~ "June",
        "7" ~ "July",
        "8" ~ "August",
        "9" ~ "September",
        "10" ~ "October",
        "11" ~ "November",
        "12" ~ "December")
  )
  select(snp_df, year, month, close)
```

```{r, unemployment}
unemploy_df = 
  read_csv("fte_data/unemployment.csv") |> 
  janitor:: clean_names() |> 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment rate?"
  )
```

## Problem 2 
```{r}
mr_trash = 
  readxl::read_excel("trash_data/202207 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:M549") |> 
  janitor::clean_names() |> 
  mutate(
    year = as.numeric(year), 
    name = "mr_trash_wheel",
    homes_powered = (weight_tons *500)/30)

prof_trash = 
    readxl::read_excel("trash_data/202207 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:L96") |> 
  janitor::clean_names() |> 
  mutate(
    name = "prof_trash_wheel",
    homes_powered = (weight_tons *500)/30)

gwy_trash = 
  readxl::read_excel("trash_data/202207 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", range = "A2:J108") |> 
  janitor::clean_names() |>
  mutate(
    name = "gwynnda_trash_wheel",
    homes_powered = (weight_tons *500)/30)

trash_tidy = 
  bind_rows(mr_trash, prof_trash, gwy_trash) |> 
  select(name, everything())
```

Need to still write paragraph - want clarity on code before finishing the problem 

## Problem 3 
```{r}
bl_data = 
  read_csv("mci_data/MCI_baseline.csv", skip = 1, col_names = TRUE) |> 
  janitor::clean_names() |> 
  mutate(
    sex = 
      case_match(
        sex, 
        0 ~ "female",
        1 ~ "male"),
    sex = as.factor(sex),
    apoe4 = 
      case_match(
        apoe4, 
        0 ~ "non-carrier",
        1 ~ "carrier"),
      apoe4 = as.factor(apoe4))

amy_data = 
  read_csv("mci_data/mci_amyloid.csv", skip = 1, col_names = TRUE) |> 
  janitor::clean_names()

##mci_tidy = 
 # bind_cols(
   # bl_data, amy_data,
   # .name_repair = c("unique"))
```

